[tool.poetry]
name = "inbrief-linker"
version = "0.1.0"
description = ""
authors = ["Sergey Okunkov <sergeyokunkov@yandex.ru>", "Nikita Rydanov <find.art.in.living@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
elasticsearch = "8.8.0"
pydantic = "2.0.2"
tqdm = "4.65.0"
torch = "^2.0.1"
transformers = "^4.30.2"
gensim = "3.8.0"
nltk = "^3.8.1"
pymorphy3 = "^1.2.0"
scikit-learn = "^1.3.0"
pydantic-settings = "^2.0.2"
fastapi = "^0.101.1"
uvicorn = "^0.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
